os: linux
dist: bionic
language: generic
services:
- docker
before_script:
- hack/prepare.sh
script:
- hack/build.sh
deploy:
- provider: script
  script: hack/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: EOp/iClw0oQUWLcoxAgkAdpQK2jQcK/9s0RhmAP24rlOobvJxb8mkjSyW1FLxzvHj88hTsnV929z5Es6X8B5RubmNQmuCE+sNmbyhFlKlM1k0ivw6emqVUlQhJD/htc80Pmz3cdtMRlD94GC1+hMIdLTPgVziJPZ7RIVOgNYVMOaVKoSLfppRKtUyZVlFpB4iZ/iqY35XtBfHjyUePcC0vtQ7eoIGkLNimor8pX1FW4ZvW2UtSo7p4UgEggKhU97erlxY38Wnh/PaFJgIyZ3XIpKmT4awukzqiPdHhECnwoorzzcdSQYidwqobvPwLbNKLD1W8r8+NnmxEcO3TFDFLIvaN3Qpo9QovkrKNJtHTKQl3YjrAnNkni3uI88GDkbaBCqfJlGfZ7K7umBDuJuXjpVpbZAWVVUpc4/WjaX/iv3kYSbEf14kRAwEIbiaa52EXiJCtIxh2rb2vfSd9Ec/6BvGrkLGTamRUl8XWWpONtUttGw5zMI8PPEImauqYna98cC3jrPuh7h/I5LiupOTgnsiPMIoX1bltuAn88OqJbNEaTRe0ABD3i30qRCdXNMsvaHbz4MhYBg++ldBH3hXTu4UKLn9k8lUG8mh9qHCNrMjRp/Z4NWPgxmHa9wOGF7fb67Kzh53Y3VjH75rft1TpkEOpsE3YFPZ5xgn3I00sE=
  - secure: W9QWmzrgS5zLH9mHT/EId2VaSP6b4fChaAW7Pq8+MZQelF3B4Y5fcQCy8miQApVUrq6OayGU9KgNn7bbiVV2ptDvsMbSShwM5FGcIiIFBAGQRoki1bQPkaX/drqTdTW2GwiXjpFpMrw2gd18aVFDYj+rcu/OwXs2yqJ8R/JpBq4I/P7soVdR1Abc/nMshqjimcGX++h5m5bEEa8s5GBXMCnf8Y7oGJlUHpjlCFevUiCPF+mc3Nj+T970ugbNuoGlqQbCApHA4gqgroYWwj1jH8ZVmZAd+tdVvHRxuG9sHP5wY7S1mXXseOVDlFGfw+YZqOQv9hyf/SdTPUpmxptIPxM6hY4C/1r3zk2xgLWuIrrn+jK5xL/kTByYFUVx+qEixrE/lW0BRp5T18kRlbYuHINQXgWK2U0GKEkCH4woTqYhA8WulZ80RaL5azrZVix7/6iuSOx8dFLBk4sKRujlyeUUAssmZx0N+QMffIMexSo0lafyUMn6BUiSmVHqAYQlLFOr7NTvsFW/v5wVjxT8EfTN+GLnkvd4eQvHA/FYsqYVcYVSvTEkNh3LL1HSfRX0Lopa/KmmSVoTXpWDBMW3oBgZoi67Vz+IcVw97hIRDyaLOEsLI4dPN2lTz5iMQHgSl5eptjWC5IAbJLiB90QCRuhi8LmCqNe+twqjtFzBlS0=
